version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k5u0o7b3

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t sampleimage ./angular/
      - echo Tagging the Docker image...
      - docker tag sampleimage:latest public.ecr.aws/k5u0o7b3/sampleimage:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push public.ecr.aws/k5u0o7b3/sampleimage:latest
      - echo Build completed on `date`